- platform: generic
  name: camera front door
  still_image_url: http://192.168.68.136:8080/cgi-bin/snapshot.sh?res=high&watermark=yes
  stream_source: rtsp://192.168.68.136/ch0_0.h264
  username: !secret camera_username
  password: !secret camera_password

- platform: generic
  name: camera solarium
  still_image_url: http://192.168.68.135:8080/cgi-bin/snapshot.sh?res=high&watermark=yes
  stream_source: rtsp://192.168.68.135/ch0_0.h264
  username: !secret camera_username
  password: !secret camera_password

- platform: generic
  name: camera Side
  still_image_url: http://192.168.68.183:8080/cgi-bin/snapshot.sh?res=high&watermark=yes
  stream_source: rtsp://192.168.68.135/ch0_0.h264
  username: !secret camera_username
  password: !secret camera_password
