- platform: doods
  url: "http://XX.XX.XX.XX:8080"
  detector: default
  scan_interval: 10000
  confidence: 60
  file_out:
    - "/tmp/{{ camera_entity.split('.')[1] }}_latest.jpg"
    - "/tmp/{{ camera_entity.split('.')[1] }}_{{ now().strftime('%Y%m%d_%H%M%S') }}.jpg"
  source:
    - entity_id: camera.camera_front_door
    - entity_id: camera.camera_solarium
  labels:
    - cat
    - dog