- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /home
    - type: memory_use
    - type: processor_use
    - type: processor_temperature


- platform: template
  sensors:
    # Le thermostat Sinope
    watt_gym_thermostat:
      friendly_name: "Gym Thermostat Watt"
      unit_of_measurement: "W"
      value_template: "{{ state_attr('climate.neviweb130_climate_thermostat', 'wattage') * (state_attr('climate.neviweb130_climate_thermostat', 'heat_level')/100) }}"
    cost_gym_thermostat:
      friendly_name: Cost Gym Thermostat
      unit_of_measurement: kWh
      value_template: "{{ '%.2f' | format(((states('sensor.watt_gym_thermostat') | float) * states('input_number.energy_cost_first_40') | float)) }}"

- platform: template
  sensors:
    daily_energy_cost:
      entity_id: sensor.energy_spent
      value_template: "{{ '%.2f' | format(((states('sensor.daily_energy_first_40') | float * states('input_number.energy_cost_first_40') | float) + (states('sensor.daily_energy_after_40') | float * states('input_number.energy_cost_after_40') | float) + states('input_number.energy_access_fee') | float) | round(2)) }}"
