
default_config:
stream:
system_health:
frontend:
  themes: !include_dir_merge_named themes

# Configure a default setup of Home Assistant (frontend, api, etc)
homeassistant:
  currency: CAD
  customize: !include customize.yaml
  media_dirs:
    camera_front_door: /config/www/camera_front_door
    camera_solarium: /config/www/camera_solarium
# all integrations are under /integrations folder
aws: !include integrations/aws.yaml
automation: !include automations.yaml
camera: !include integrations/cameras.yaml
climate: !include integrations/climate.yaml
garbage_collection: !include integrations/garbage_collection.yaml
group: !include integrations/groups.yaml
hilo: !include integrations/hilo.yaml
ios: !include integrations/ios.yaml
media_player: !include integrations/media_player.yaml
neviweb130: !include integrations/neviweb.yaml
nissan_leaf: !include integrations/nissan_leaf.yaml
sensor: !include integrations/sensors.yaml
utility_meter: !include integrations/utility_meter.yaml
recorder: !include integrations/recorder.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
sonoff: !include integrations/sonoff.yaml
tts: !include integrations/tts.yaml
weather: !include integrations/weather.yaml