
default_config:
stream:
frontend:
  themes: !include_dir_merge_named themes

# Configure a default setup of Home Assistant (frontend, api, etc)
homeassistant:
  customize: !include customize.yaml
  media_dirs:
    camera_front_door: /config/www/camera_front_door
    camera_solarium: /config/www/camera_solarium
# all integrations are under /integrations folder
camera: !include integrations/cameras.yaml
group: !include integrations/groups.yaml
automation: !include automations.yaml
script: !include integrations/scripts.yaml
scene: !include integrations/scenes.yaml
ios: !include integrations/ios.yaml
sensor: !include integrations/sensors.yaml
recorder: !include integrations/recorder.yaml
neviweb130: !include integrations/neviweb.yaml
media_player: !include integrations/media_player.yaml
weather: !include integrations/weather.yaml
hilo: !include integrations/hilo.yaml
sonoff: !include integrations/sonoff.yaml
utility_meter: !include integrations/utility_meter.yaml
nissan_leaf: !include integrations/nissan_leaf.yaml